on: [push]

name: Test

jobs:
  test:
    name: Rust project
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
              ~/.cargo/registry
              ~/.cargo/git
          key: ${{ runner.os }}-${{ github.sha }}
          restore-keys: ${{ runner.os }}-
      - run: |
            cargo build --release
      - run: |
            cargo test --release
